version: '3.8'

services:
  catmicroservice:
    build: 
      context: ./CatMicroservice
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./CatMicroservice:/app
      - /app/node_modules
    env_file:
      - ./CatMicroservice/.env
    command: npm start

  dogmicroservice:
    build: 
      context: ./DogMicroservice
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    volumes:
      - ./DogMicroservice:/app
      - /app/node_modules
    env_file:
      - ./DogMicroservice/.env
    command: npm start

  loginmicroservice:
    build: 
      context: ./LoginMicroservice
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    volumes:
      - ./LoginMicroservice:/app
      - /app/node_modules
    env_file:
      - ./LoginMicroservice/.env
    command: npm start

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:3000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - catmicroservice
      - dogmicroservice
      - loginmicroservice
    command: npm start