version: '3.8'

services:
  catmicroservice:
    image: retroandre/catmicroservice:latest
    ports:
      - "3001:3001"

  dogmicroservice: 
    image: retroandre/catmicroservice:latest
    ports:
      - "3002:3002"

  loginmicroservice:
    image: retroandre/loginmicroservice:latest
    ports:
      - "3003:3003"

  frontend:
    image: retroandre/frontend:latest
    ports:
      - "8080:3000"
    depends_on:
      - catmicroservice
      - dogmicroservice
      - loginmicroservice
    command: npm start