version: '3.8'

services:
  catmicroservice:
    image: retroandre/catmicroservice:latest
    ports:
      - "3001:3001"
    volumes:
      - ./CatMicroservice:/app
      - /app/node_modules
    env_file:
      - ./CatMicroservice/.env
    command: npm start

  dogmicroservice: 
    image: retroandre/catmicroservice:latest
    ports:
      - "3002:3002"
    volumes:
      - ./DogMicroservice:/app
      - /app/node_modules
    env_file:
      - ./DogMicroservice/.env
    command: npm start

  loginmicroservice:
    image: retroandre/loginmicroservice:latest
    ports:
      - "3003:3003"
    volumes:
      - ./LoginMicroservice:/app
      - /app/node_modules
    env_file:
      - ./LoginMicroservice/.env
    command: npm start

  frontend:
    build:
    image: retroandre/frontend:latest
    ports:
      - "8080:3000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - catmicroservice
      - dogmicroservice
      - loginmicroservice
    command: npm start